### PR TITLE
Feature auto direction mixed RTL and LTR

### LINKED ISSUE #18: Support text direction per line/paragraph
Hey good man,
Will u make it go RTL for only the scope (or the line) in which I make the RTL/LTR switch , not the whole note?
Mixing directions in the same note is needed please!! 

image

### PR DESCRIPTION
**Pull request by zoli**
This enables auto direction for a file, Which each line direction will get determined by first meaningful character.

Closes #18, #34, #31

### CODE REVIEW

**Comment by zoli** [comment]
I made it draft because I wanted to ask why you don't put the styles in `styles.css` file? I mean STH like this:
```
this.replacePageStyleByString('List indent fix',
			`/* List indent fix */ .is-rtl .HyperMD-list-line { text-indent: 0px !important; }`, true);
```
From which I see `.is-rtl .HyperMD-list-line { text-indent: 0px !important; }` can be in styles.css file without any problem.

Because of `replacePageStyleByString` function `styles.css` gets removed each time that I switch from a file which is auto direction to a file which is in LTR direciton. And I can't use styles.css file. If its necessary I need to apply my styles like what you did.

**Comment by zoli** [comment]
After this. The only serious problem I see is on cursor movement. In RTL areas when I press left arrow at the end of line it goes to line before instead of line after. The overall behavior is buggy. I'm not sure why, because I didn't saw this in codemirror examples.

**Comment by zoli** [comment]
I moved styling to `styles.css` file and made some fixes on styling.

**Comment by zoli** [comment]
I think this is ready for review and maybe getting merged if there isn't any breaking or problem. I've been using it for the last two weeks.

**Comment by pourmand1376** [comment]
Thanks, this seems interesting to me. Can you attach compiled files to test it locally?

**Comment by esm7** [comment]
Thank you for this so important piece of work!
I tried to pull and it test it, and:

1. When building, I get the error:
```
(!) Plugin typescript: @rollup/plugin-typescript TS2339: Property 'registerEditorExtension' does not exist on type 'RtlPlugin'.
main.ts: (42:8)

42      this.registerEditorExtension(autoDirectionPlugin);
```

And when copying the resulting `main.js` to the plugin directory, Obsidian refuses to load with the following error:
```
An error occurred while loading Obsidian. Error: Unrecognized extension value in extension set ([object Object]). This sometimes happens because multiple instances of @codemirror/state are loaded, breaking instanceof checks.
```

Any clue what went wrong?

**Comment by zoli** [comment]
At first I got the `multiple instances of @codemirror/state` error to and I couldn't resolve it until switching to latest version of https://github.com/obsidianmd/obsidian-sample-plugin `package.json` but after a while building with current `package.json` didn't made any problem either.
Could you try building with this patch (it switches to current obsidian-sample-plugin `package.json`):
```
diff --git a/package.json b/package.json
index 7ca8ce3..7b95719 100644
--- a/package.json
+++ b/package.json
@@ -4,21 +4,22 @@
   "description": "RTL (Right to Left) language support for Obsidian.",
   "main": "main.js",
   "scripts": {
-    "dev": "rollup --config rollup.config.js -w",
-    "build": "rollup --config rollup.config.js"
+    "dev": "node esbuild.config.mjs",
+    "build": "tsc -noEmit -skipLibCheck && node esbuild.config.mjs production",
+    "version": "node version-bump.mjs && git add manifest.json versions.json"
   },
   "keywords": [],
   "author": "",
   "license": "MIT",
   "devDependencies": {
-    "@rollup/plugin-commonjs": "^15.1.0",
-    "@rollup/plugin-node-resolve": "^9.0.0",
-    "@rollup/plugin-typescript": "^6.1.0",
-    "@types/node": "^14.14.2",
-    "codemirror": "^5.62.0",
-    "obsidian": "https://github.com/obsidianmd/obsidian-api/tarball/master",
-    "rollup": "^2.33.0",
-    "tslib": "^2.0.3",
-    "typescript": "^4.0.5"
+    "@types/node": "^16.11.6",
+    "@typescript-eslint/eslint-plugin": "5.29.0",
+    "@typescript-eslint/parser": "5.29.0",
+    "builtin-modules": "3.3.0",
+    "esbuild": "0.14.47",
+    "obsidian": "latest",
+    "prettier": "^2.7.1",
+    "tslib": "2.4.0",
+    "typescript": "4.7.4"
   }
 }
```

Also you should add https://github.com/obsidianmd/obsidian-sample-plugin/blob/master/esbuild.config.mjs file in root directory.

**Comment by esm7** [comment]
Sorry for the holdup, I really want to merge this PR this week, but going back to this error and trying what you suggested seems to make things worse -- I now get many, many more errors :sweat: 

```
auto-dir-plugin.ts:8:8 - error TS2307: Cannot find module '@codemirror/view' or its corresponding type declarations.

8 } from "@codemirror/view";
         ~~~~~~~~~~~~~~~~~~

auto-dir-plugin.ts:9:39 - error TS2307: Cannot find module '@codemirror/state' or its corresponding type declarations.

9 import { RangeSetBuilder, Text } from "@codemirror/state";
                                        ~~~~~~~~~~~~~~~~~~~

auto-dir-plugin.ts:41:29 - error TS7006: Parameter 'fromA' implicitly has an 'any' type.

41     vu.changes.iterChanges((fromA, toA, fromB, toB) => {
                               ~~~~~

auto-dir-plugin.ts:41:36 - error TS7006: Parameter 'toA' implicitly has an 'any' type.

41     vu.changes.iterChanges((fromA, toA, fromB, toB) => {
                                      ~~~

auto-dir-plugin.ts:41:41 - error TS7006: Parameter 'fromB' implicitly has an 'any' type.

41     vu.changes.iterChanges((fromA, toA, fromB, toB) => {
                                           ~~~~~

auto-dir-plugin.ts:41:48 - error TS7006: Parameter 'toB' implicitly has an 'any' type.

41     vu.changes.iterChanges((fromA, toA, fromB, toB) => {
                                                  ~~~

auto-dir-plugin.ts:177:16 - error TS7006: Parameter 'v' implicitly has an 'any' type.

177  decorations: (v) => v.decorations,
                   ~

main.ts:42:8 - error TS2339: Property 'registerEditorExtension' does not exist on type 'RtlPlugin'.

42   this.registerEditorExtension(autoDirectionPlugin);

```

Would you mind trying to add whatever configuration changes are needed to the PR itself, then try to get to a situation that you clone it into a new directory, install it and build?

**Comment by zoli** [comment]
Sorry for the trouble. I should have done this at first.
After the last commit now `npm install` and `npm run build` works for me on fresh clone.

**Comment by esm7** [comment]
The good news is that I manage to get it to work now!
The bad news is that there are many issues :(

1. When setting the direction to `AUTO` nothing seems to happen, and the document is actually updated only when the cursor is moved inside it.
2. The more serious problem is that the cursor behaves wrong when the mode is AUTO. For example, in full RTL mode, if I press the right arrow on the keyboard and keeps pressing, it gets to the beginning of the line (as it should) and then continues to the last (left-most) position of the previous line, and continues right. In AUTO mode, if I keep pressing right, after reaching the beginning of the line (on the right) it jumps to the left, and the next press jumps to the line *below* rather than above. Also, the Home key jumps to the end of the line (left), and End to the beginning (right). Any clue how to fix these?

**Comment by zoli** [comment]
I haven't faced the first issue, I will look into it. I'm aware of second issue but I haven't figured out a way to solve it yet. I have a hunch that its related to codemirror or even obsidian cursor managing level. It seems that the direction should get set at the parent level not per element for solving the issue which isn't possible in mixed rtl ltr.

**Comment by esm7** [comment]
Ok, so: the good news is that I dug deep into the CodeMirror code and forums to try and understand the issue of the cursor movement, and I was able to get it to work *perfectly*!
The bad news is that with the `dir=auto`  decoration, most of your internal plugin code seems to be redundant, and CodeMirror handles this very well according to the standard Unicode algorithm :-O

I made a commit & push to this branch, mind taking a look and testing it out?

There is still the pending issue that the view updates between auto and non-auto only upon an editor update (e.g. a document change), I'll try later today to find a way to push a refresh.

**Comment by zoli** [comment]
@esm7 Thanks for your efforts. I'm testing it right now, I will write my comments.

- one thing to note is using auto direction makes specific styling for rtl/ltr impossible. see some of styles that I have put in styles.css file.
- moving cursor is much better now, still moving from one line to next line has problem
- in auto direction selecting a bullet list line with rtl text and then clicking to deselect makes it ltr

**Comment by zoli** [comment]
- auto direction doesn't work on markdown preview for me, Its all ltr
- also before this auto direction was working in kanban mode to and thats not working either

**Comment by esm7** [comment]
As the one who understands better than me the majority of your changes, would love your help fixing these :pray:

**Comment by esm7** [comment]
> @esm7 Thanks for your efforts. I'm testing it right now, I will write my comments.
> 
>     * one thing to note is using `dir=auto` direction makes specific styling for rtl/ltr impossible. see some of styles that I have put in styles.css file.
> 
>     * moving cursor is much better now, still moving from one line to next line has problem
What problem are you seeing?
One thing I'm aware of is that if you have a series of lines that change directions, e.g. an LTR line and then an RTL line, and then again and LTR line, holding "left" for example will enter a confusing loop, because on the RTL line it means "go next" and then when you move to the LTR line it says "go previous"... I think that shouldn't be regarded as a bug, but the expected behavior, even if confusing.

> 
>     * in auto direction selecting a bullet list line with rtl text and then clicking to deselect makes it ltr
Still trying to understand this one. I think it's something about Obsidian's styling that's causing it, because the line styling doesn't change, and even if I inspect the line in the inspector, it jumps back!

**Comment by zoli** [comment]
> Still trying to understand this one. I think it's something about Obsidian's styling that's causing it, because the line styling doesn't change, and even if I inspect the line in the inspector, it jumps back!

I was looking to this right now, It seems that the direction is somehow miscalculated in the middle. Because the rendering puts the `text-indent` on the left instead of right.

> What problem are you seeing?

Looking more carefully at this, I see that it happens again in bullet lists not normal text. And I don't mean mixed RTL and LTR lines. Two bullet list line which both are RTL pressing left arrow key moves to the next line but pressing it again moves back to line before. Without bullet list works fine.

I think both these problems are rooted in the bullet maybe it somehow sees the bullet as LTR character.

**Comment by esm7** [comment]
> 



> > Still trying to understand this one. I think it's something about Obsidian's styling that's causing it, because the line styling doesn't change, and even if I inspect the line in the inspector, it jumps back!
> 
> I was looking to this right now, It seems that the direction is somehow miscalculated in the middle. Because the rendering puts the `text-indent` on the left instead of right.
> 
> > What problem are you seeing?
> 
> Looking more carefully at this, I see that it happens again in bullet lists not normal text. And I don't mean mixed RTL and LTR lines. Two bullet list line which both are RTL pressing left arrow key moves to the next line but pressing it again moves back to line before. Without bullet list works fine.

I can't seem to recreate this :( Can you paste an example? Unless you already have a solution ;-)

> 
> I think both these problems are rooted in the bullet maybe it somehow sees the bullet as LTR character.

I can't be completely sure, but I'm getting the feeling that the issue with bullets is caused by the code that Obsidian uses to convert the `-` into a bullet when the cursor moved away from it. That's where it seems to break. If we get to the conclusion we have no way to work-around this, we can release it as-is and I'll talk to licat who will hopefully cooperate and fix it from the Obsidian side.

**Comment by esm7** [comment]
I have a fix! Basically setting `unicode-bidi: plaintext` on `.cm-line` fixes the algorithm's confusion during the switch from `-` to a bullet, and after doing that, some CSS tweaks are needed to fix some further visual glitches in this switch.

**Comment by esm7** [comment]
@zoli I'm trying to bring back the reading view support (which I destroyed by shamelessly removing the Markdown post-processor you wrote :facepalm:), but there's something that I don't understand.
How does it work with regard to adjacent lines on the same paragraph that should have different directions?
To my understanding, something like -
```
LTR line
RTL line
LTR line
```
Translates in Reading View to a single `div` with a single `<p>` element, separated by `<br>` breaks.
How is possible to give these lines different directions?

**Comment by zoli** [comment]
Hmm. You are right I had not faced the situation and wasn't aware of the problem.

> How is possible to give these lines different directions?

I don't see anyway to do that except the solution you said.

**Comment by zoli** [comment]
>  I can't seem to recreate this :( Can you paste an example? Unless you already have a solution ;-)


https://user-images.githubusercontent.com/3286303/213547462-cad9a64a-3ccb-47b5-9fcd-6b3e4d953aa6.mp4

**Comment by zoli** [comment]
Investigating more on the cursor movement problem. I think the cursor movement can't get solved in a good way at plugin level. Maybe speaking to licat to get an idea of how the cursor movement is handled could help.

**Comment by esm7** [comment]
> Investigating more on the cursor movement problem. I think the cursor movement can't get solved in a good way at plugin level. Maybe speaking to licat to get an idea of how the cursor movement is handled could help.
> 
> Also about styling alongside with auto dir the solution comes to my mind is adding classes, Which that also adds the redundancy of manually calculating the line direction based on the content.

I didn't yet write a proper code for my `unicode-bidi: plaintext` idea, but it does seem to solve the issue of bullets. Hope I'll manage to spend the time on it later today and have something for you to cast an opinion on.

**Comment by zoli** [comment]
> I didn't yet write a proper code for my unicode-bidi: plaintext idea, but it does seem to solve the issue of bullets

I manually added the style and checked, I think it solves the bullet list becoming LTR on selection with some glitches that as you said its probably fixable by css styling. But the cursor movement that I made a video earlier still exists.

**Comment by esm7** [comment]
There's a dilemma here...
Should we let CodeMirror and the HTML Unicode algorithm manage the logic and live with the few glitches it introduces, with the advantage of clean, minimal code, **or** revert to the full logic that you wrote, that controls the logic from scratch, seems to work more reliably (I believe the cursor issues are solvable) but contains much more code to maintain, things that can break on future versions of CodeMirror, and possible small bugs that we haven't thought of?
What do you think?

**Comment by zoli** [comment]
> What do you think?

In the long run I hope that someday obsidian will support RTL internally. For the CodeMirror part I'm relieved as its open source the community can implement the feature and also the last time I asked for better RTL support they made the feature available really fast.
I think patching cursor movement at plugin level will be hard to maintain (there is no api and etc problems). About the direction handling I prefer going with auto direction (although I don't like the strong direction based on first character) but the styling is annoying.
I use obsidian almost on daily base writing both in Farsi and English. Using this plugin on top of this branch was working almost good for the past month and the almost part is because of cursor movement.

Overall I would suggest not trying to solve the cursor movement part at least for now and communicate with obsidian team.

**Comment by esm7** [comment]
So, in order to experiment, I brought back the custom logic that you wrote for deciding on LTR/RTL for each line, and merged that with some of my fixes, so we seemingly now get the best of both worlds: cursor movement seems to work well, switching updates immediately and I didn't notice any side-effects.
Reading view still needs work on breaking multi-direction `div`s.
I'll experiment with this version for a while, and would love another opinion on whether it's a good idea to maintain all this custom logic for the benefit of seemingly a very well-working solution -- but with lots of things that can break...
(Another advantage for this approach is that it allows some custom logic like the treatment of `- [x]` that you wrote, which I really like)

**Comment by zoli** [comment]
> custom logic like the treatment of - [x] that you wrote, which I really like

Oh, Actually I had totally forgotten that :). It was one of my reasons not going with direction auto.

**Comment by zoli** [comment]
It would be really good if other users tested this to. Probably they will give some insights.

**Comment by esm7** [comment]
> It would be really good if other users tested this to. Probably they will give some insights.

I'll write the paragraph-breaking code for Reading View and once it works I'll invite others to give this a try.

**Comment by esm7** [comment]
I wrote the code that breaks paragraphs and Reading View seems to work really nice now.
I also wrote some CSS rules to handle callouts and YAMLs better, and revamped the settings mechanism which really needed a refactor.
@zoli before merging and releasing this I'd love your help in one last thing. Can you please add a few comments in AutoDirPlugin.ts and styles.css? There are styles that you wrote which I don't understand their intention, and although in AutoDirPlugin I believe I understand it all, some documentation from you will surely be helpful for future maintenance.

Additionally, one potential source of issues is the big `STRONG_DIR_REGEX` in `globals.ts`. If this was adapted from some documentation, example or source, can you document that and refer to it?

**Comment by zoli** [comment]
Thanks, Sure will do it in coming days.

**Comment by esm7** [comment]
In the meantime, I'll release the version, I think it's ready for prime time :)

**Pull request merged**
